### ISSUE TITLE
Check your internet connection dialogue and close the camera activity

### ISSUE THREAD

**Issue by mome13** [blinkcard/blinkcard-android#10]
I created the app using your tutorial and after starting the camera activity it tells me that check your internet connection and want to close the activity.

**Comment by culoi** [comment]
Hi @mome13 

Versions 2.0.0 and above require an internet connection to work under our new License Management Program.

We’re only asking you to do this so we can validate your trial license key. Scanning or data extraction of credit cards still happens offline, on the device itself. Once the validation is complete, you can continue using the SDK in offline mode (or over a private network) until the next check.

Best regards

**Comment by mome13** [comment]
HI

it is completely ok but I have a strong connection and it still persists on error. how to fix it ?

**Comment by mparadina** [comment]
Hi @mome13 

How often does the "internet connection" alert pop-up you enter the scanning screen?
Every time you enter it, or less?

Regards,
Milan

**Comment by mome13** [comment]
Every time I entered the camera activity!

**Comment by anjapenic** [comment]
Hi @mome13 

Please contact us at support@microblink.com so we could gain a better understanding of the matter since this looks like it might be a license issue.

Regards,
Anja

**Comment by dhiraj** [comment]
This is happening to me as well. The sample app uses the old SDK and that works perfectly fine on the same device, but every time I try to use my trial license, the moment I enter the recognizer activity, it shows a dialog like in screenshot.

Please fix or update instruction docs on how to make the Internet connection check succeed, it is failing *every* time. The device has a strong Internet connection on WiFi, and I've asked for `<uses-permission android:name="android.permission.INTERNET" />` in the app manifest as well. minSDK is 21, target and compile SDKs are at 29. 

![Screenshot_20210202-221226_BlinkCard](https://user-images.githubusercontent.com/43901/106693135-ce4a9100-65a3-11eb-9d98-b41d2bdc626a.jpg)

**Comment by anjapenic** [comment]
Hello @dhiraj,

Could you please contact us at support@microblink.com with more details so we could check if this is a license issue? 

Regards,
Anja

**Comment by dhiraj** [comment]
Adding these two perms in the Android Manifest seems to fix the Check Internet Connection problem! 🎉 
```xml
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by anjapenic** [comment]
Hello @dhiraj, 

Glad it worked! Is there anything else we could help you with?

Regards,
Anja
