### ISSUE TITLE
Do not find sample to support Automation Testing.

### ISSUE THREAD

**Issue by codewithvikas** [blinkcard/blinkcard-android#24]
Before opening an issue, check that you are using the latest version of the BlinkCard SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/blinkcard/blinkcard-android#-frequently-asked-questions-and-known-problems)
---
### Description
I want to perform unit test as well as automation test. Do you have any support for this ?
### Environment Details

**Comment by anjapenic** [comment]
Hello @codewithvikas,

Could you give us a bit more info on what exactly do you need?

You can find our sample app which demonstrates BlinkCard SDK integration here - https://github.com/blinkcard/blinkcard-android/tree/master/BlinkCardSample.

Best regards,
Anja

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
