### ISSUE TITLE
FaceImage returns null

### ISSUE THREAD

**Issue by damolaobaleke** [blinkcard/blinkcard-android#25]
### Description

On BlinkIdRecognizer Result gotten, the getFaceImage() method returns null. There's no faceImage gotten. All other info is processed fine

<img width="1390" alt="Screenshot 2021-12-29 at 16 41 42" src="https://user-images.githubusercontent.com/45045727/147712986-92f7281b-456b-474a-9147-5176071756f3.png">

### Environment Details

**BlinkCard version:**
com.microblink:blinkcard:2.5*

**Device model:**
Samsung SM-A307FN

**Device Android version:**
Android 11, Api 30

**Device ABI (processor architecture, e.g. ARMv7):**
ARMv7
### Log file

Please enable logging by following instructions [here](https://github.com/blinkcard/blinkcard-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by anjapenic** [comment]
Hi @damolaobaleke,

Could you share with us which SDK are you using? Are you using both BlinkID and BlinkCard SDKs in your project? 

When setting your recognizer, have you set the [setReturnFaceImage](http://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/BlinkIdCombinedRecognizer.html#setReturnFaceImage(boolean)) to true? For example, like this:

```
        recognizer = new BlinkIdRecognizer();
        recognizer.setReturnFaceImage(true);
        recognizerBundle = new RecognizerBundle(recognizer);
```

Best regards,
Anja

**Comment by damolaobaleke** [comment]
@anjapenic Thanks, I didn't know that method existed so i hadn't set it to true. I'd try that out.

**Comment by damolaobaleke** [comment]
@anjapenic This `recognizer.setReturnFaceImage(true);` fixed it. Thanks !
