### ISSUE TITLE
Is there way to hide/disable icon torch and close on scan screen

### ISSUE THREAD

**Issue by tamtps** [blinkcard/blinkcard-android#30]
Hi [AntonioErdeljac](https://github.com/AntonioErdeljac)
Can we hide/disable icon torch and close on the scanning screen? 
Because my toolbar has a close icon so we need to hide it when integrating your SDK.

Thanks,
TamNguyen

**Comment by Brankacro** [comment]
Hello @tamtps,
If you are using our default UI settings, then you can not disable it; only if you are building your [custom](https://github.com/blinkcard/blinkcard-android#-custom-ux-with-recognizerrunnerview) integration.
In case of any questions, please let us know, and feel free to contact us directly at support@microblink.com.

**Comment by tamtps** [comment]
[AntonioErdeljac](https://github.com/AntonioErdeljac)
Do you have a sample for custom UI integration?
Another one, is Microblink SDK does it have a recognized card is real or fake (card physical or photo)?

Thanks,
TamNguyen

**Comment by Brankacro** [comment]
We do not have a sample for custom UI integration, just the [link](https://github.com/blinkcard/blinkcard-android#-custom-ux-with-recognizerrunnerview) provided.
Regarding the recognition, we are not verifying if the card is real or fake.
Please let us know in case of any additional questions.

**Comment by tamtps** [comment]
https://github.com/Brankacro
I saw your lib can support scanning more than 1700 credit and debit cards on website https://microblink.com/identity/credit-card-scanning/
so can you provide me the list of cards that support?

Thanks,
TamNguyen
