### ISSUE TITLE
Not getting card image

### ISSUE THREAD

**Issue by samirpramanik** [blinkcard/blinkcard-android#4]
Hello,

I am trying to scan cards using BlinkCard however i am not able to get the card image. The other fields are coming fine such as cardNumber, issuer and expiry date. I am using the version 1.0.0. I tried result.getFullDocumentFrontImage and getEncodedFrontFullDocumentImage, but both return null.
Please find our implementation below :
`private BlinkCardRecognizer mRecognizer;
    private RecognizerBundle mRecognizerBundle;
    public static final int MY_REQUEST_CODE = 0x222;

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // create BlinkCardRecognizer
        mRecognizer = new BlinkCardRecognizer();
        mRecognizer.setExtractCvv(false);

        // bundle recognizers into RecognizerBundle
        mRecognizerBundle = new RecognizerBundle(mRecognizer);
        startScanning();
    }

    public void startScanning() {
        // Settings for BlinkCardActivity Activity
        BlinkCardUISettings settings = new BlinkCardUISettings(mRecognizerBundle);

        // tweak settings as you wish

        // Start activity
        ActivityRunner.startActivityForResult(this, MY_REQUEST_CODE, settings);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        try {
            if (requestCode == MY_REQUEST_CODE) {
                if (resultCode == BlinkCardActivity.RESULT_OK && data != null) {
                    // load the data into all recognizers bundled within your RecognizerBundle
                    mRecognizerBundle.loadFromIntent(data);

                    // now every recognizer object that was bundled within RecognizerBundle
                    // has been updated with results obtained during scanning session

                    // you can get the result by invoking getResult on recognizer
                    BlinkCardRecognizer.Result result = mRecognizer.getResult();
                    if (result.getResultState() == Recognizer.Result.State.Valid) {
                        // result is valid, you can use it however you wish
                        String cardNumber = result.getCardNumber();

                        CardIssuer issuer = result.getIssuer();
                        String owner = result.getOwner();
                        DateResult validity = result.getValidThru();
                        Image cardImage = result.getFullDocumentFrontImage();
                        ByteArrayOutputStream fos = new ByteArrayOutputStream();
                        byte[] byteArray = result.getEncodedFrontFullDocumentImage();
                        if(byteArray != null ){
                            String base64CardImage = Base64.encodeToString(byteArray, Base64.DEFAULT);
                        }

                    }
                }
            }`

![BlinkCardIssue](https://user-images.githubusercontent.com/48544382/60393422-3a425900-9b26-11e9-8a1c-fccf79e72e2c.PNG)

**Comment by samirpramanik** [comment]
And also, we are not getting the owner name. Is there any other API to fetch the same?

**Comment by i1E** [comment]
Hi @samirpramanik,

you have to enable returning of full document image on the recognizer instance, use [BlinkCardRecognizer.setReturnFullDocumentImage](https://blinkcard.github.io/blinkcard-android/com/microblink/entities/recognizers/blinkcard/BlinkCardRecognizer.html#setReturnFullDocumentImage-boolean-).

By default, owner name is not extracted, you also have to enable that feature, use [BlinkCardRecognizer.setExtractOwner](https://blinkcard.github.io/blinkcard-android/com/microblink/entities/recognizers/blinkcard/BlinkCardRecognizer.html#setExtractOwner-boolean-).

Hope this helps.
